### ISSUE TITLE
Facing Error while executing

### ISSUE THREAD

**Issue by ayamgupta** [shriram1998/PedestrianSpeedEstimator#1]
Hey I am new to this can you help me out with the error?

YOLOv5 🚀 1888663 torch 1.13.1+cu117 CPU

Fusing layers... 
Model Summary: 308 layers, 21041679 parameters, 0 gradients
WARNING: --img-size [720, 1280] must be multiple of max stride 32, updating to [736, 1280]
Traceback (most recent call last):
  File "/home/ayamgupta/ps/PedestrianSpeedEstimator/track.py", line 325, in <module>
    detect(opt)
  File "/home/ayamgupta/ps/PedestrianSpeedEstimator/track.py", line 145, in detect
    pred = model(img, augment=opt.augment, visualize=visualize)
  File "/home/ayamgupta/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayamgupta/ps/PedestrianSpeedEstimator/yolov5/models/common.py", line 384, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "/home/ayamgupta/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayamgupta/ps/PedestrianSpeedEstimator/./yolov5/models/yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/ayamgupta/ps/PedestrianSpeedEstimator/./yolov5/models/yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "/home/ayamgupta/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ayamgupta/mambaforge/lib/python3.10/site-packages/torch/nn/modules/upsampling.py", line 157, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "/home/ayamgupta/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by shriram1998** [comment]
Hi,
    Seems to be an issue with yolov5 package and its dependencies. You could search for possible solutions. Here is a good starting point (https://github.com/ultralytics/yolov5/issues/6948)

**Comment by ayamgupta** [comment]
Thanks. resolved the issue. also the latest pytorch version conflicts. It works perfectly now.
